projeto/ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('loja/', include('loja.urls'), name="loja"),
    #path('', include('loja.urls'), name="homepage"),
]
 

projeto/loja/urls.py
from django.urls import path
from . import views

app_name = 'loja'

urlpatterns = [
    # /loja/
    path('', views.index, name='index'),
    # /loja/1/
    path('<int:produto_id>/', views.detail_produto, name='detail_produto'),
    # /add_item
    path('add_item/', views.add_item, name='add_item'),
    # /add_pedido
    path('add_pedido/', views.add_pedido, name='add_pedido'),
    # /clientes
    path('clientes/', views.clientes, name='clientes'),
    
    # /loja/cliente/1
    # TODO
    
    # /add_produto
    path('add_produto/', views.add_produto, name='add_produto'),
]

projeto/loja/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Produto(models.Model):
    # TODO

    def __str__(self):
        return self.nome

class Cliente(models.Model):
    # TODO 

    def __str__(self):
        return self.nome

class Pedido(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    valor_total = models.DecimalField(max_digits=20, decimal_places=2, default=0.0)
    pago = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)+ " --- "+ str(self.cliente) + " --- " + str(self.valor_total)

class ItemPedido(models.Model):
    produto = models.ForeignKey('Produto', on_delete=models.PROTECT)
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(validators=[MinValueValidator(1)])

    class Meta:
        unique_together = ('pedido', 'produto')

    def __str__(self):
        return f"({self.pedido}) - ({self.produto})"

projeto/loja/views.py
from django.shortcuts import render
from .models import ItemPedido, Produto, Cliente, Pedido

def index(request):
  all_products = Produto.objects.all()
  return render(request, 'loja/produtos.html', {'produtos': all_products})

def detail_produto(request, produto_id):
  produto = Produto.objects.get(id=produto_id)
  return render(request, 'loja/detalhe_produto.html', {'produto': produto})

def add_pedido(request):
  return render(request, 'loja/pedido.html')

def add_item(request):
  all_products = Produto.objects.all()
  all_clientes = Cliente.objects.all()
  if request.method == 'GET':
    return render(request, 'loja/pedido.html', {'produtos': all_products, 'clientes': all_clientes, 'pedido': ''})  
  elif request.method == 'POST':
    produto_id = request.POST['produto']
    quantidade = request.POST['quantidade']
    if request.POST.get('pedido','') == '':
      cliente_id = request.POST['solicitante']
      cliente = Cliente.objects.get(pk=cliente_id)
      pedido = Pedido(cliente=cliente, valor_total=0, pago=False)
      pedido.save()
    else:
      pedido = Pedido.objects.get(pk=request.POST['pedido'])
      cliente = Cliente.objects.get(pk=request.POST['solicitante'])
    
    item = ItemPedido(produto = Produto.objects.get(pk=produto_id), pedido = pedido, quantidade = quantidade)
    item.save()
    return render(request, 'loja/pedido.html', {'produtos': all_products, 
      'cliente': cliente, 'pedido': pedido.id, 'itens': ItemPedido.objects.filter(pedido=pedido)})
    
def clientes(request):
  #TODO
  pass 

def detail_cliente(request, cliente_id):
  #TODO
  pass

def add_produto(request):
  try:
    p = Produto.objects.create(
      nome = request.POST['nome'], 
      descricao = request.POST['descricao'], 
      preco = request.POST['preco'])
    p.save()
    return render(request, 'loja/detalhe_produto.html', {'produto': p})
  except:
    return render(request, "loja/add_produto.html")

projeto/loja/templates/loja/add_produto.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<hr style="width:100%">

<form action="{% url 'loja:add_produto' %}" method="post">
  {% csrf_token %}

  <label for="nome">Nome:</label><br>
  <input type="text" id="nome" name="nome"><br>
  <label for="lname">Descrição:</label><br>
  <input type="text" id="descricao" name="descricao"><br>
  <label for="lname">Preço:</label><br>
  <input type="number" id="preco" name="preco"><br>
  <input type="submit" value="Cadastrar"><br>
  </form>

{% endblock %}

projeto/loja/templates/loja/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Loja do Tio Zé</title>
  </head>

  <body style="background-color:darkgray">
    <h1>Loja do Tio Zé: aqui você encontra de tudo!</h1>
    {% block content %} {% endblock %}

    <hr style="width:100%">
    <h2>
      [<a href="{%url 'loja:index' %}">Produtos</a>]
      [<a href="{%url 'loja:clientes' %}">Clientes</a>]
      [<a href="{%url 'loja:add_item' %}">Novo Pedido</a>]
    </h2>
  
  </body>
</html>

projeto/loja/templates/loja/clientes.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<hr style="width:100%">

<h2> Lista de clientes </h2>

<ul>
    <ul>
      {% for cliente in clientes %}
      <li><h3><a href="{% url 'loja:detail_cliente' cliente.id %}">{{ cliente.nome }}</a></h3></li>
      {% endfor %}
    </ul>
</ul>
{% endblock %}

projeto/loja/templates/loja/detail.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

produto... 

{% endblock %}

projeto/loja/templates/loja/detalhe_cliente.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<hr style="width:100%">

<h2> Cliente {{ cliente.nome }} </h2>

<ul>
    <ul>
      <li><b>Nome:</b> {{cliente.nome}} </li>
      <li><b>CPF:</b> {{cliente.cpf}} </li>
      <li><b>Endereço:</b> {{cliente.endereco}} </li>
    </ul>
</ul>

{% endblock %}

projeto/loja/templates/loja/detalhe_produto.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<hr style="width:100%">

<h2> Produto {{ produto.nome }} </h2>

<ul>
    <ul>
      <li><b>Descrição</b> {{produto.descricao}} </li>
      <li><b>Preço</b> {{produto.preco}} </li>
    </ul>
</ul>

<hr style="width:100%">
    <h2>
      [<a href="{%url 'loja:add_produto' %}">Novo Produto</a>]
    </h2>

{% endblock %}

projeto/loja/templates/loja/error.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<h1>ops.... algo não deu certo!</h1> 

{% endblock %}

projeto/loja/templates/loja/pedido.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

{% if pedido == '' %}

<form action="{% url 'loja:add_item' %}" method="post">
    {% csrf_token %}

    <label for="solicitante">Selecione o cliente:</label>
    <select id="solicitante" name="solicitante" size="4" single>
        {% for cliente in clientes %}
        <option value="{{cliente.id}}">{{cliente.nome}}</option>
        {% endfor %}
    </select><br><br>

    <label for="produto">Escolha um produto:</label>
    <select id="produto" name="produto" size="4" single>
        {% for produto in produtos %}
        <option value="{{produto.id}}">{{produto.nome}}</option>
        {% endfor %}
    </select><br><br>
    <label for="quantidade">e a quantidade: </label>
    <input type="number" id="quantidade" name="quantidade"><br><br>
    
    <button type="submit" value="submit">Adicionar item</button>
</form>

{% else %}

<form action="{% url 'loja:add_item' %}" method="post">
    {% csrf_token %}

    <h2>Cliente: {{cliente.nome}}</h2>
    <h2>Número do pedido: {{pedido}}</h2>
    <h2>Itens no pedido: </h2>

    <ul>
        <ul>
          {% for item in itens %}
          <li><h3>{{ item }}</h3></li>
          {% endfor %}
        </ul>
    </ul>

    <br><br>

    <input type="hidden" value="{{cliente.id}}" name="solicitante" />
    <input type="hidden" value="{{pedido}}" name="pedido" />

    <label for="produto">Escolha um produto para adicionar ao pedido:</label>
    <select id="produto" name="produto" size="4" single>
        {% for produto in produtos %}
        <option value="{{produto.id}}">{{produto.nome}}</option>
        {% endfor %}
    </select><br><br>
    <label for="quantidade">e a quantidade: </label>
    <input type="number" id="quantidade" name="quantidade"><br><br>
    
    <button type="submit" value="submit">Adicionar item</button>
</form>


{% endif %}


{% endblock %}

projeto/loja/templates/loja/produtos.html
{% extends "loja/base.html" %}
{% load static %}

{% block content %}

<hr style="width:100%">

<h2> Aqui estão os nossos produtos... </h2>

<ul>
    <ul>
      {% for produto in produtos %}
      <li><h3><a href="{% url 'loja:detail_produto' produto.id %}">{{ produto.nome }}</a></h3></li>
      {% endfor %}
    </ul>
</ul>
{% endblock %}